"""add a subscribe class

Revision ID: 86abb84197f8
Revises: 9e4a13f37453
Create Date: 2021-09-27 11:59:03.860581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86abb84197f8'
down_revision = '9e4a13f37453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscibe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscibe_email'), 'subscibe', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscibe_email'), table_name='subscibe')
    op.drop_table('subscibe')
    # ### end Alembic commands ###
